env-test/FamillyShare/FamillyShare/Models/ErrorViewModel.cs
using System;

namespace FamillyShare.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

env-test/FamillyShare/FamillyShare/Models/Photo.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace FamillyShare.Models
{
    public class Photo
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }

        public string PhotoUrl { get; set; }

        [NotMapped] 
        public IFormFile PhotoFile { get; set; }
    }
}

env-test/FamillyShare/FamillyShare/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FamillyShare.Models;

namespace FamillyShare.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

env-test/FamillyShare/FamillyShare/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using FamillyShare.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FamillyShare.Controllers
{
    public class PhotoController : Controller
    {
        private readonly IWebHostEnvironment _env;

        public PhotoController(IWebHostEnvironment env)
        {
            _env = env;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Photo item)
        {
            ModelState.Remove(nameof(Photo.PhotoUrl));

            if (ModelState.IsValid)
            {
                IFormFile photoFile = item.PhotoFile;

                string extension = Path.GetExtension(photoFile.FileName);

                if (extension == ".png" || extension == ".jpg")
                {
                    string newFileName = item.Name;

                    if (photoFile.Length > 0)
                    {
                        string filePath = Path.Combine(_env.WebRootPath, "images", newFileName + extension);
                        item.PhotoUrl = "images/" + newFileName + extension;

                        using (FileStream fs = new FileStream(filePath, FileMode.Create))
                        {
                            await photoFile.CopyToAsync(fs);
                        }
                        TempData["Message"] = "Téléchargement réussi.".ToBootstrapAlerts("success");
                        return RedirectToAction(nameof(Index));
                    }
                }


            }
            TempData["Message"] = "Opération échouée.".ToBootstrapAlerts("danger");
            return View(nameof(Index));
        }
    }
}

env-test/FamillyShare/FamillyShare/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

env-test/FamillyShare/FamillyShare/Views/Photo/Index.cshtml
@model FamillyShare.Models.Photo
@{ ViewData["Title"] = "Index"; }


<partial name="_Message" /> 

<h4>Photo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhotoFile" class="control-label"></label>
                <input type="file" name="photoFile" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

env-test/FamillyShare/FamillyShare/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FamillyShare</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FamillyShare</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Photo" asp-action="Index">Uploader</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FamillyShare - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

env-test/FamillyShare/FamillyShare/Views/Shared/_Message.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<div id="messages">
    @if (ViewData["Message"] != null)
        @Html.Raw(ViewData["Message"])

    @if (TempData["Message"] != null)
        @Html.Raw(TempData["Message"])
</div>